package-lock.json
package.json
server/db/models/category.js
server/db/models/index.js
server/db/models/product.js

Create product and category tables #1

---

client/components/Products.js
client/components/SingleProduct.js

ProductsCompleteSingleProductInProcess

---

script/seed.js
server/db/models/category.js
server/db/models/index.js

Seed file #5

---

server/api/index.js
server/api/products.js

Api all products #6

---

client/components/Products.js

Set up Products.js dummy data

---

client/components/Products.js
client/components/SingleProduct.js
client/routes.js
package-lock.json

Issue4 continued

---

server/api/products.js

wrote api route to get one product by id

---

server/api/products.js

Api products by category

---

client/components/Products.js
client/components/SingleProduct.js
client/components/index.js
client/routes.js
client/store/index.js
client/store/product.js

Completed work in card 17+20 
- added product reducer to root reducer (in combineReducers)
- fetched product list from backend on Route componentDidMount (in loadInitialState)
- connected Products component to state (removed dummy data)
- connected SingleProduct component to state
---

Display the products from the backend

---

server/api/categories.js
server/api/index.js
server/api/products.js

Created two more api routes:
api/categories serves up a list of the categories
api/categories/:categoryId serves up the details of a single category

Added api/categories and api/categories/categoryId

---

client/components/Products.js

Issue17 Continued

---

.travis.yml
package.json

deploy fixing

---

package.json

added  && node script/seed.js to postinstall in package.json

---

client/components/Products.js
client/components/Search.js

working on search form

---

client/components/Products.js
client/components/Sidebar.js
public/style.css

Sidebar on products page

---

client/components/Search.js

search is working, but need to capitalize first letter of fruit

---

client/components/Search.js

search by product name is working

---

client/components/Products.js
client/store/product.js

Edit form #38

---

client/components/Products.js

Accepted current change for products component merge

---

client/components/Search.js

fix formatting of mapStateToProps in all components

---

client/components/Products.js
client/components/Sidebar.js
client/components/navbar.js
server/db/models/index.js
server/db/models/order.js
server/db/models/user.js

Order table #59

---

client/components/Products.js
client/components/Sidebar.js
client/components/navbar.js

Added announcement of currently viewed category to products component

---

server/db/models/index.js
server/db/models/order_products.js

Added quantity and unitPrice attributes to OrderProducts table

---

server/api/categories.js
server/api/products.js

feat(stati): add conventional HTTP stati to backend routes

---

script/seed.js

added images to seed file

---

client/components/Products.js
public/style.css

set flex-wrapping to productCards class

---

client/store/cart.js

Working on Cart Reducer

---

server/api/products.spec.js

feat(test): products backend api routes get requests test

---

server/api/products.spec.js
server/db/models/order.spec.js
server/db/models/order_products.spec.js

Note to Rebecca: I included a test for the delete product route. All the tests except that one should pass as is, and that one should pass once you create the delete product route, assuming you set it up to be called using '.delete(/api/products/:productId)'

Order products model tests #76

---

client/store/product.js

feat(delete): add to redux store

---

client/components/SingleProduct.js
client/components/navbar.js
client/store/product.js

Add delete button #84

---

client/store/cart.spec.js

final test of cart action creators and reducer

---

package.json

Set up google OAth

---

client/components/AllOrders.js
server/db/models/order.js

add isShipped attribute to Order model

---

script/seed.js

Seeded orders and OrderProducts lines

---

server/api/index.js
server/api/orders.js
server/api/orders.spec.js

get all orders backend route done

---

server/api/orders.js
server/db/models/index.js

fix(routes): eager load GET routes for order api routes

---

client/store/order.js
server/api/orders.js

feat(order): add redux store for SingleOrder component

---

server/api/orders.spec.js

test specs for backend api/orders

---

client/components/Cart.js

Cart displays total in dollars

---

client/app.js
client/components/Cart.js
client/components/Checkout.js
client/components/CheckoutForm.js
client/components/user-home.js
package-lock.json
package.json
public/index.html
server/api/index.js
server/api/payment.js

Stripe integration on checkout

---

script/seed.js
server/api/cart.js
server/api/index.js
server/api/payment.js
server/db/models/order.js

backend route to post a cart order and total price field on order

---

client/components/Cart.js
client/components/Cart.spec.js

Writing tests for cart component

---

client/components/Cart.js
client/components/Checkout.js
client/store/cart.js
client/store/cartOrder.js
client/store/cartOrder.spec.js
client/store/index.js
server/api/cart.js
server/api/payment.js
server/db/models/order.js

Find order by user

---

client/components/Cart.js
client/components/Cart.spec.js
client/components/Checkout.js
client/store/helper.js
client/store/helper.spec.js
package-lock.json

TotalPriceLinkedToCheckoutPage

---

client/components/Cart.js
client/components/navbar.js
client/store/helper.js

added total price on cart to create order and to send to Stripe

---

client/components/Checkout.js
client/components/CheckoutForm.js
client/store/cartOrder.js

update order status to complete upon Stripe checkout

---

server/api/payment.js

changed stripe secret keys

---

client/components/AddtoCartToast.js
client/components/SingleProduct.js
client/store/index.js
client/store/toasts.js

adding a toast to acknowledge item added to cart

---

client/components/AddProduct.js
client/components/ProductCard.js
client/components/Products.js
client/components/Search.js
client/components/Sidebar.js
package-lock.json
public/index.html

styling changes

---

client/components/SingleProduct.js

solve merge conflicts in single product component

---

client/components/Cart.js
client/components/CheckoutForm.js
client/components/SingleProduct.js
client/routes.js
client/store/cart.js
client/store/index.js
server/api/index.js
server/api/session.js
server/index.js

Cart refresh 151

---

client/components/CheckoutForm.js
client/components/SingleProduct.js

standardized all axios to be lowercase

---

client/components/SingleProduct.js

added toast to single product component

---

client/components/SingleProduct.js

Unauthenticated users checkout #164

---

client/components/AddtoCartToast.js
client/components/SingleProduct.js

added style and timeout to toast

---

client/components/Checkout.js
client/components/CheckoutForm.js
client/store/cartOrder.js
server/api/cart.js
server/api/orders.js
server/api/orders.spec.js

backend route for products-orders creation and updated cart store

---

client/components/Checkout.js
client/components/CheckoutForm.js

adding thunk for creating order-products instances

---

client/components/Cart.js
client/store/cart.js
package-lock.json

Editing items in cart

---

client/components/Cart.js
client/components/PromptCheckout.js
client/routes.js

feat(popup): add popup login box on checkout

---

client/components/Checkout.js
client/components/CheckoutForm.js
client/store/cartOrder.js
client/store/helper.js
server/api/orders.js
server/api/orders.spec.js

able to populate order-products table

---

client/components/ChartProducts.js
client/components/ChartUsers.js
client/components/Welcome.js
client/components/navbar.js
client/routes.js
public/style.css
server/api/analytics.js
server/api/products.js

Api security 211

---

client/routes.js

Accessing non-authoriezd pages brings back to welcome pag

---

script/seed.js

Seeded orderProducts table

---

README.md
client/components/Cart.js
client/components/SingleOrder.js

Edit unitprice singleorder #204

---

client/components/SingleProduct.js

fix(price): add unit price to single product view

---

client/components/Welcome.js
client/components/navbar.js
client/components/user-home.js
client/routes.js

Welcome page 207

---

client/components/ChartOrders.js
client/components/ChartProducts.js
client/components/ChartUsers.js
client/components/FruitFriends.js
client/store/user.js
server/api/analytics.js

Analytics 200

---

client/app.js
client/components/AddProduct.js
client/components/Cart.js
client/components/SingleProduct.js
server/db/models/product.js

Add submit button to add product page
set add to cart dropdown default to 1
---

Hook to render product in cents

---

client/components/CheckoutConfirmation.js
client/components/CheckoutForm.js
client/store/helper.js

added order confirmation component

---

client/components/AddProduct.js
client/components/EditProduct.js

Add and Edit Form Styled

---

client/components/Checkout.js
client/components/CheckoutForm.js
client/store/helper.js

Add form validation upon checkout

---

client/components/AddProduct.js
client/components/Cart.js

Styling cart final

---

client/components/SingleProduct.js

Button links single product page back to main

---

client/components/AddProduct.js
client/components/SingleProduct.js
server/db/models/product.js

Correcting price calculation

---

script/seed.js

Seed file admin #218

---

client/components/SingleOrder.js

Singleorder total price0#253

---

client/components/AddProduct.js

added form validations to add product form

---

script/seed.js

Product descriptions

---

client/components/AddProduct.js
client/components/AddtoCartToast.js
client/components/Analytics.js
client/components/Cart.js
client/components/ChartOrders.js
client/components/ChartProducts.js
client/components/ChartUsers.js
client/components/Checkout.js
client/components/CheckoutConfirmation.js
client/components/EditProduct.js
client/components/FruitFriends.js
client/components/LogoutConfirmation.js
client/components/Products.js
client/components/Search.js
client/components/Sidebar.js
client/components/SingleProduct.js
client/components/navbar.js
client/components/user-home.js
client/store/cartOrder.js
client/store/category.js
client/store/product.js
server/api/categories.js
server/api/orders.spec.js
server/api/payment.js
server/api/products.js
server/api/session.js

Remove console logs #186

---

script/seed.js

descriptions up to line 77

---

client/components/AddProduct.js

fixing add product form validations

---

client/components/ProductCard.js

feat(price): add product price to all products view

---

client/components/AddProduct.js

change describe to Describe in add product form
